### ISSUE TITLE
Telegraf example dashboards templatize / tag the grafana host, not puppetdb / puppetserver nodes

### ISSUE THREAD

**Issue by suckatrash** [puppetlabs/puppetlabs-pe_metrics_dashboard#24]
`SHOW TAG VALUES WITH KEY = "host"` returns the hostname of the grafana host

**Comment by jarretlavallee** [comment]
This one was my fault. It looks like this query following query will allow for pulling the correct servername, but each of the data queries has to be updated to `where server =~ /$host/`

![screen shot 2017-11-08 at 5 44 43 pm](https://user-images.githubusercontent.com/25229952/32542153-b06e6166-c4ac-11e7-9d5b-5c85a7ef2620.png)

**Comment by jarretlavallee** [comment]
After looking into this, it is a limitation of httpjson since we cannot ingest any real tags. We are working around this with regexes, but the real fix will be to change from httpjson to jolokia2 when telegraf [1.5](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md) is released. This will give us more flexibility in which metrics are pulled and which tags are associated with each metric. For now I will update the templated variables to accommodate it, but the aliases will suffer since we cannot run regexes on those.

**Comment by suckatrash** [comment]
Closing this was fixed by PR #26
